linters:
  enable:
    - deadcode
    - errcheck
    - gosimple
    - govet
    - staticcheck
    - structcheck
    - typecheck
    - unused
    - bodyclose
    - dupl
    - gosec
    - varcheck
    - godox

run:
  tests: false
