version: 2.1

orbs:
  nancy: ory/nancy@0.0.8
  golangci: ory/golangci@0.0.2

jobs:
  test:
    docker:
      -
        image: circleci/golang:1.13
    working_directory: /go/src/github.com/ory/jsonschema
    steps:
      - checkout
      -
        run: make tools
      -
        run: go-acc -o coverage.txt ./... -- -v -failfast -timeout=20m -tags sqlite
      -
        run: bash <(curl -s https://codecov.io/bash)

workflows:
  test:
    jobs:
      - nancy/test
      - golangci/lint
      - test